---
title: "Working With Rasters"
description: |
  Visualizing raster data in R.
date: 2021-02-27
output:
  distill::distill_article:
    code_folding: true
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(raster)
library(tidyverse)
library(here)
library(sf)
library(fasterize)
library(rnaturalearth)
library(rnaturalearthdata)
```

```{r}
# read in data

cetacean_richness <- here("data", "ca_cetaceans")

cetaceans <- dir(cetacean_richness, full.names = TRUE, pattern = "*.tif")

cetaceans_stack <- stack(cetaceans)

# threshold function
is_present <- function(x, thresh = .75) {
  y <- ifelse(x >= thresh, 1, NA)
  return(y)
}

# calculating species richness 
cetaceans_richness <- calc(cetaceans_stack, fun = is_present)

species_richness <- calc(cetaceans_richness, fun = sum, na.rm = TRUE)
```

Here I read in a raster stack and wrote a function to determine the presence of cetacean speices. After applying the function, I calculated overall cetacean species richness and then converted the raster to a dataframe. Finally, I visualized the result by layering raster data with spatial data from the rnaturalearthdata package.

```{r, results = FALSE, fig.cap = "Map of cetacean species richness in the California Bight, using a threshold of 75% probability of occurence to determine presence for each species."}

# download ca coastline layer from rnaturalearth
coastline <- ne_download(scale = "medium", type = 'land', category = 'physical', returnclass = "sf")

# convert raster to data frame
species_richness_df <- raster::rasterToPoints(species_richness) %>% 
  as.data.frame()

ggplot() +
  geom_raster(data = species_richness_df, aes(x = x, y = y, fill = layer)) +
  geom_sf(data = coastline, fill = "lavender") +
  coord_sf(xlim = c(-125,-115), ylim = c(33,37)) +
  scale_fill_gradient(low = "skyblue4", high = "seagreen3") +
  theme_void() 

```


