---
title: "About Me"
description: |
  Experience, Skills and Interests
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Skills and Interests
I aim to center the next chapter of my career on advancing clean energy and climate solutions. To that end, I pursued my graduate studies at Bren where I specialized in Energy and Climate with a focus on Strategic Environmental Communication and Media. I built a strong technical skill set and fostered a budding interest in data science. Going forward, I hope to leverage my experience with data analysis and visualization to help solve environmental problems.

Through my Masters Group Project and coursework, I gained conceptual, technical and communication skills to investigate and answer environmental questions with data. In analyzing real-world datasets using R, RStudio and GitHub, I have practiced data exploration, analysis and project management. Some of the skills I have developed include data wrangling, exploratory data analysis, descriptive statistics, hypothesis testing, describing uncertainty, and data visualization. I also picked up a few more advanced methods for analyzing environmental data, including logistic regression and spatial analysis. Additionally, I learned about data management and practiced using tools such as the bash command language to manipulate files and the SQL query language to create and query databases.

### Experience

Before completing my Master of Environmental Science and Management degree, I spent over five years working with the Northern Sierra Partnership (NSP), a collaborative initiative comprising five conservation organizations. As the Deputy Campaign Director, I helped coordinate NSP’s joint fundraising campaigns and supported the protection and stewardship of the region between Lake Tahoe and Mt. Lassen. Prior to joining the Partnership, I graduated from Stanford University (2014) with a B.S. in Earth Systems. During my undergraduate career, I focused my coursework on environmental policy and co-authored a paper titled “All Over the Map: The Diversity of Western Water Plans,” which was published in the California Journal of Politics and Policy. The year after I graduated, I served as an AmeriCorps Volunteer with Sequoia Riverlands Trust in Visalia, CA. 

