---
title: "Chloropleth Map"
description: |
  Spatial data visualization using ggplot.
output:
  distill::distill_article:
    code_folding: true
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(knitr)
library(tidyverse)
library(here)
library(janitor)
library(sf)
library(tmap)
```

```{r, results=FALSE}
# read in data

ca_counties <- read_sf(here("data", "ca_counties"), layer = "CA_Counties_TIGER2016") %>% 
  clean_names() %>% 
  select(name)

oil_spills <- read_sf(here("data", "ds394"), layer = "ds394") %>% 
  clean_names() 

# check projection
st_crs(ca_counties)
st_crs(oil_spills)

ca_counties <- st_transform(ca_counties, st_crs(oil_spills)) # transforms to same crs as oil spill dataset

```

Here I created a static map in ggplot illustrating inland oil spill events by county. After joining spatial data for CA counties with a dataset for oil spills in the state, I used geom_sf() to create a chloropleth map in which the fill color depended on the count of inland oil spill events by county.

```{r, fig.cap="**Figure 1:** Total inland oil spills by county in 2008"}
# combine data sets to bid spill counts to counties
county_spills <- ca_counties %>% 
  st_join(oil_spills)

spills_count <- county_spills %>% 
  filter(inlandmari == "Inland") %>% 
  count(name)

ggplot(data = spills_count) +
  geom_sf(aes(fill = n), color = "lightgray", size = 0.2) +
  scale_fill_gradientn(colors = c("white","orange","red")) +
  theme_minimal() +
  labs(fill = "Number of inland oil spills")
```


